// Copyright 2025 Surviving Gloomspire Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

// Log Categories
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSurvivingGloomspire, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Game, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Gameplay, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_AI, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_UI, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Inventory, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_AbilitySystem, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_EffectSystem, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_EventSystem, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_ConfigSystem, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Loading, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Net, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Physics, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Audio, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Animation, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_Input, Log, All);
SURVIVINGGLOOMSPIRE_API DECLARE_LOG_CATEGORY_EXTERN(LogSG_SaveGame, Log, All);
